### PR TITLE
Separated nested classes in to their own files & added namespace

### LINKED ISSUE #7: [Proposal]: Separate Vertex, Edge, Loop, and Face in to their own files
### Summary
Move the Vertex, Edge, Loop, and Face classes that are nested in the BMesh class in to their own classes and files.

### Motivation
It would make the BMesh class smaller and easier to read and edit, and allows for easier editing and reading of multiple classes at once. Using the BMesh API currently requires additional boilerplate because it requires you to either declare a static using of the BMesh class, or preface every reference with `BMesh.` (eg `BMesh.Vertex`).
The current implementation also does not follow the  C# [design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) making it looks less consistent, clean, and intuitive.

### Drawbacks
This is a breaking change, if anyone were referencing the nested types directly (eg `BMesh.Vertex`) they would need to change the usage from `BMesh.Vertex` to just `Vertex`.

I would be more than willing to make a PR for this, but thought it better to make an issue for it for easier discussion first.

### PR DESCRIPTION
**Pull request by MechWarrior99**
### Summary
Separated all nested classes that were in `BMesh` in to their own classes and files.
Moved all classes to their own namespace `BMeshLib`.
Removed unused `using` statements.

### Feedback
1. Is the namespace `BMeshLib` adequate? _If_ the name of the project is changed (see #10 ) then this should be changed to match.
2. `AttributeValue` and related class files are in the folder `MeshAttributes`, should this be changed? `BMeshAttributes`, or maybe `AttributeValues`?

Closes #7

### CODE REVIEW

**Comment by eliemichel** [comment]
1. Sounds good, I like `BMeshLib`
2. I think `AttributeValues` would be easier for discoverability when reading the code.

**Comment by eliemichel** [comment]
Also, what happend to `BMeshOperators.cs` and `BMeshUntity.cs` the diff is a bit convoluted, is it just because of indentation changes? Afaik I was using Visual Studio's default formatting rules.

**Comment by MechWarrior99** [comment]
Okay, sounds good!

I see what you mean, that diff is rather convoluted. It could be a combination of removing the unused `using`s and moving them in to a namespace? They both look fine with normal formatting, and those are the only two things I changed in them.

**Comment by eliemichel** [comment]
Thanks!

**Comment by eliemichel** [comment]
(Merged in the "v2" branch rather than master)

**Pull request merged**
